sonar.projectKey=tp-gpf1
sonar.projectName=TP-GPF1
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.inclusions=app.js,bin/**,routes/**,controllers/**,services/**,prisma.config.ts

sonar.exclusions=node_modules/**,generated/**,public/**,prisma/migrations/**,coverage/**

sonar.cpd.exclusions=prisma/migrations/**,generated/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.test.inclusions=tests/**
