sonar.projectKey=tp-gpf1
sonar.projectName=TP-GPF1
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

# Scope analysed files
sonar.sources=.
sonar.inclusions=app.js,bin/**,routes/**,controllers/**,services/**,prisma.config.ts

# Exclusions
sonar.exclusions=node_modules/**,generated/**,public/**,prisma/migrations/**

# ESLint-based projects typically don't use default CPD on generated/migration files
sonar.cpd.exclusions=prisma/migrations/**,generated/**
